---
- name: Create GCP VM Instance
  hosts: localhost
  gather_facts: no
  vars_files:
    - vars.yaml

  tasks:
    - name: Authenticate to GCP
      command: >
        gcloud auth activate-service-account --key-file {{ credentials_file }}

    - name: Set project
      command: gcloud config set project {{ project_id }}

    - name: Launch VM using gcloud
      command: >
        gcloud compute instances create {{ instance_name }}
        --zone {{ zone }}
        --machine-type {{ machine_type }}
        --image-family {{ image_family }}
        --image-project {{ image_project }}
